apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netlifytrial
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netlifytrial
    app.kubernetes.io/part-of: netlifytrial
  name: netlifytrial
spec:
  rules:
  - host: netlifytrial-pshivpuj-tenant.$121.ip.io
    http:
      paths:
      - backend:
          service:
            name: netlifytrial
            port:
              number: 3001
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
